SourceCode/WebEnterprise_2/WebEnterprise_2/Controllers/TutorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebEnterprise_2.Filters;
using WebEnterprise_2.Models;
using WebEnterprise_2.Utils;

namespace WebEnterprise_2.Controllers
{
    public class TutorController : Controller
    {
        DataContext dbc = new DataContext();
        // GET: Tutor
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Register()
        {
            return View();
        }
        public ActionResult Login()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Login(String id, String password)
        {
            var manager = dbc.Turtors.SingleOrDefault(m => m.Username == id && m.Pass == password);
            if (manager == null)
            {
                ModelState.AddModelError("", "Wrong ID!");
            }
            else
            {
                ModelState.AddModelError("", "Login Successfully!");
                XSession.Tutor = manager;
                return View();
            }

            return View();
        }
        [HttpPost]
        public ActionResult Register(Turtor model)
        {
            try
            {
                dbc.Turtors.Add(model);
                dbc.SaveChanges();
                ModelState.AddModelError("", "Regist Successfully !");
            }
            catch
            {
                ModelState.AddModelError("", "Regist Fail!");
            }
            return View();
        }
        [Authenticate]
        public ActionResult Post()
        {
            ViewBag.StudentId = new SelectList(dbc.Students, "Id", "Fullname");
            return View();
        }
        [HttpPost]
        public ActionResult Post(Report model)
        {

            ViewBag.StudentId = new SelectList(dbc.Students, "Id", "Fullname");
            var file = Request.Files["UpImage"];
            if (file != null)
            {
                model.Documents = Guid.NewGuid() + file.FileName.Substring(file.FileName.LastIndexOf("."));
                file.SaveAs(Server.MapPath("~/Documents/" + model.Documents));
            }
            else
            {
                model.Documents = "Product.png";
            }

            model.TutorId = 1;
            dbc.Reports.Add(model);
            dbc.SaveChanges();
            var list = new List<string>();
            list.Add(XSession.Tutor.Email);
            
            var body = "<h1>The new report is posted</h1>";
            var student = dbc.Students.Find(model.StudentId);
            list.Add(student.Email);
            Xmailer.Send(list, "Report", body);
            
            return RedirectToAction("Post");
        }

        public ActionResult Logout()
        {
            XSession.RemoveTutor();
            return View("Login");
        }
    }
}

SourceCode/WebEnterprise_2/WebEnterprise_2/Views/Tutor/ErrorEmail.cshtml
@{
    ViewBag.Title = "ErrorEmail";
}

<h2>SMTP Server is being fixed now</h2>

SourceCode/WebEnterprise_2/WebEnterprise_2/Views/Tutor/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

SourceCode/WebEnterprise_2/WebEnterprise_2/Views/Tutor/Login.cshtml
@{
    ViewBag.Title = "Login";
}

<section id="form">
    <!--form-->
    <div class="container">
        <div class="row">
            <div class="col-sm-6 col-sm-offset-1">
                <div class="login-form">
                    <!--login form-->
                    <h2>Login to your account</h2>
                    @Html.ValidationSummary()
                    @using (Html.BeginForm())
                    {
                        @Html.Hidden("ReturnUrl", "@ViewBag.ReturnUrl")
                        <div class="form-group">
                            <label>ID</label>
                            @Html.TextBox("Id", null, new { @class = "form-control" })
                        </div>
                        <div class="form-group">
                            <label>Password</label>
                            @Html.Password("Password", null, new { @class = "form-control" })
                        </div>

                        <div class="form-group">
                            @*<button class="btn btn-danger">Submit</button>*@
                            <button id="send2" name="send" type="submit" class="button login"><span>Login</span></button>

                        </div>
                    }
                </div><!--/login form-->
            </div>

        </div>
    </div>
</section>

SourceCode/WebEnterprise_2/WebEnterprise_2/Views/Tutor/Post.cshtml
@model WebEnterprise_2.Models.Report
@{
    ViewBag.Title = "Post";
}

<h2>Post</h2>
@using (Html.BeginForm("Post", "Tutor", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <div class="form-group">
        <label>Meeting</label>
        @Html.TextBoxFor(model => model.Meeting, new { @class = "form-control" })
    </div>
    <div class="form-group">
        <label>Comments</label>
        @Html.TextAreaFor(model => model.Comments, new { @class = "form-control" })
    </div>
    <div class="form-group">
        <label>Student</label>
        @Html.DropDownList("StudentId", null, new { @class = "form-control" })
    </div>
    <div class="form-group">
        <label>Image</label>
        <input type="file" name="UpImage" class="form-control" />
        @Html.HiddenFor(m => m.Documents)
    </div>
    <div class="form-group">
        <button class="btn btn-danger">Submit</button>
    </div>
}

SourceCode/WebEnterprise_2/WebEnterprise_2/Views/Tutor/Register.cshtml
@model WebEnterprise_2.Models.Turtor
@{
    ViewBag.Title = "Register";
}


<section id="form">
    <!--form-->
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <div class="login-form">
                    <!--login form-->
                    <h2>Register as Tutor</h2>
                    @Html.ValidationSummary(true)
                    @using (Html.BeginForm("Register", "Tutor",
                        FormMethod.Post, new { enctype = "multipart/form-data" }))
                    {


                        @Html.HiddenFor(m => m.Id, new { @class = "form-control" })


                        <div class="form-group">
                            <label>UserName</label>
                            @Html.TextBoxFor(m => m.Username, new { @class = "form-control" })

                        </div>
                        <div class="form-group">
                            <label>Password</label>
                            @Html.PasswordFor(m => m.Pass, new { @class = "form-control" })

                        </div>

                        <div class="form-group">
                            <label>Email</label>
                            @Html.TextBoxFor(m => m.Email, new { @class = "form-control" })

                        </div>
                        <div class="form-group">
                            <label>FullName</label>
                            @Html.TextBoxFor(m => m.Fullname, new { @class = "form-control" })

                        </div>
                        <div class="form-group">
                            <button class="btn btn-danger">Submit</button>
                        </div>
                    }
                </div><!--/login form-->
            </div>

        </div>
    </div>
</section>